CREATE TABLE AGRICULTURAL_OFFICER (
    OfficerID INT PRIMARY KEY AUTO_INCREMENT,
    Username VARCHAR(50) UNIQUE NOT NULL,
    Password VARCHAR(255) NOT NULL
);


INSERT INTO AGRICULTURAL_OFFICER (Username, Password)
VALUES ('officer', PASSWORD('1234')); -- Hashes the passwordvvv